export type Auth = {
  id: number;
  photo: string;
  name: string;
  username: string;
  email: string;
  email_verified_at: string;
  password: string;
  bio: string;
  gender: string;
  phone: string;
  dob: string;
  remember_token: string;
  password_confirmation: string;
  status: boolean;
  load: any;
  error: any;
  message: string;
  imgUrl: string;
};
